version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        volumes:
            - sqlvolume:/var/opt/mssql
        ports:
            - "1401:1433"
        environment:
            SA_PASSWORD: "Password1"
            ACCEPT_EULA: "Y"

volumes:
    sqlvolume: