import DateService from './DateService'

const Labels = {

    welcome: (user) => `Добро пожаловать, ${user}!`,
    error: (code, text) => `Ошибка: ${code} | ${text}`,
    hoursSelector_valueText: (title, count) => `с ${title}, ${count} час(а)`,
    phone_smsSent: (phone) => `Код успешно выслан на ${phone}`,
    booking_choiceInfo: (from, to) => `Выбрано время ${DateService.convertHourIntervalToLabel(from, to)}`,

    // messages
    logout: 'Logged out',
    bookingSaved: 'Booking saved successfully!',
    smsSent: 'Sms was sent!',
    phoneConfirmed: 'Phone confirmed!',
    loginError: 'Login error',
    registerError: 'Register error',
    defaultError: 'Something went wrong...',
    bookingCanceled: 'Booking canceled!',
    resend_success: 'Booking code was sent successfully!',
    resend_error: 'Booking code sending failed!',
    changePassword_success: 'Password changed!',
    redirectNotify: 'You will be redirected...',

    // validation
    bookingHoursIncorrectInput: 'Некорретный ввод',
    fieldIsRequired: 'This field is required',
    loginWrongUser: 'Wrong username...',
    loginWrongPass: '...or password',
    userAlreadyRegistered: 'This username already registered',
    usernameCreateRule: "Username must be 30 length maximum and contain only english letters, digits or '_'",
    passwordCreateRule: 'Password must be 5 length minimum',
    passwordConfirmFail: 'Passwords are not equal',
    phoneRule: 'Phone must be like 8 (xxx) xxx-xx-xx',
    phoneAlreadyConfirmed: 'This phone is already confirmed',
    phoneConfirmationCodeRule: 'Code must be 6 digit',
    phoneConfirmationCodeInvalid: 'Invalid code',
    currentPasswordInvalid: 'Wrong current password',

    // errors
    errorLoadCommon: 'Error occured while loading data. Try to reload.',
    errorLoginNeed: 'Login to see this page',

    // labels
    hoursSelector_label: 'Выберите часы',
    cancel: 'Cancel',
    loginForm_user: 'Username',
    loginForm_userEnter: 'Enter username',
    loginForm_pass: 'Password',
    loginForm_passEnter: 'Enter password',
    loginForm_passConfirm: 'Password Confirmation',
    loginForm_passConfirmEnter: 'Confirm password',
    loginPopup_login: 'Login',
    loginPopup_register: 'Register',
    loginPopup_toogleRegister: 'Registration',
    phone_confirm: 'Указать телефон',
    phone_change: 'Изменить телефон',
    phone_title: 'Phone',
    phone_phoneEnter: 'Enter phone',
    phone_phone: 'Phone',
    phone_codeEnter: 'Enter code',
    phone_code: 'Code',
    phone_sendCode: 'Send code',
    phone_confirmError: 'Error occured while confirming',
    phone_sendError: 'Error occured while sending code',
    phone_enterPhoneText: 'We will send you a code just to confirm that it is you phone',
    booking: 'Booking',
    bookings: 'Bookings',
    settings: 'Settings',
    userBookings_title: 'My bookings',
    userBookings_date: 'Date',
    userBookings_time: 'Time',
    userBookings_status: 'Status',
    userBookings_actions: 'Actions',
    userBookings_cancelQuestion: 'Are you sure you want to cancel booking?',
    userBookings_cancel: 'Cancel booking',
    userBookings_resendQuestion: 'Are you sure you want to resend booking code?',
    userBookings_resend: 'Resend booking code',
    userBookings_payBooking: 'Are you sure you want to pay booking?',
    userBookings_pay: 'Pay booking',
    changePass_title: 'Новый пароль',
    changePass_button: 'Изменить пароль',
    changePass_currentPass: 'Текущий пароль',
    changePass_currentPassEnter: 'Введите текущий пароль',
    changePass_newPass: 'Новый пароль',
    changePass_newPassEnter: 'Введите новый пароль',
    changePass_newPassConfirm: 'Подтверждение нового пароля',
    changePass_newPassConfirmEnter: 'Подтвердите новый пароль',
    booking_help: 'Всего три действия – бронируете время, оплачиваете репетицию, получаете код от базы.\n\nБронировать время просто: выбираете неделю, выбираете день, выбираете время.\nНеделю можно поменять, тыкая в стрелочки.\nДень – кликнув на нужный день (для каждого указано свободное время).\nВремя – выбрав желаемые часы в выпадающем списке.\n\nЧтобы забронировать время вам нужно зарегистрироваться и указать свой телефон. Во-первых, мы хотим иметь возможность связаться с вами в экстренном случае, во-вторых – телефон нужен для получения кода, с помощью которого вы попадете на базу.\n\nИ не забудьте оплатить репетицию – только после этого вам придет смс с кодом.',
    booking_helpShow: 'Помощь',
    booking_userNotLoggedIn: 'Залогиньтесь, чтобы иметь возможность бронировать время',
    booking_phoneNotConfirmed: 'Укажите телефон, чтобы иметь возможность бронировать время',
    booking_defaultInfo: 'Выберите часы, в которые вы хотите репетировать',
    booking_hoursInvalid: 'Часы выбраны некорректно – они должны идти подряд, без пропусков',
    booking_book: 'Забронировать'
}

export default Labels
